##@SectionDefault: Main
replicaCount: 1

image:
  repository: ghcr.io/cto2bpublic/passage-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
##@Section: Naming
nameOverride: passage-ui
fullnameOverride: passage-ui

##@Section: Service
# Specify port if needed - ussually its 80 http
service:
  type: ClusterIP
  name: http
  port: 80

ports:
  - name: http
    containerPort: 80
    protocol: TCP

##@Section: Ingress
ingress:
  enabled: true
  annotations:
    # This section should be left as is
    cert-manager.io/cluster-issuer: cto2b-dns
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    # change hostname
    - host: <<._metadata.instance>>.passage-dev.<<.dns.common_name>>
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        # Change hostname
        - "*.passage-dev.<<.dns.common_name>>"
      secretName: generic-app-secret-<<._metadata.instance>>

##@Section: Resources
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

metadata: {}
